model:
  class: model.mnist.MNISTModel

experiment:
  dataset: MNIST
  lr: 1.0
  data_dir: datasets/
  batch_size: 64
  test_batch_size: 1000
  num_workers: 4
  max_epoch: 14
  output_dir: checkpoints/
  device: cuda
  device_id: '0'
