hydra:
  run:
    dir: ${hydra.runtime.cwd}

model:
  class: model.mnist.MNISTModel

experiment:
  dataset: MNIST
  lr: 0.002
  data_dir: datasets/
  batch_size: 32
  validation_split: 0.3
  num_workers: 2
  max_epoch: 100
  output_dir: checkpoints/{epoch}_{val_acc:.2f}
  device: cuda
  device_id: '0'
